In [6]:
## import torch
import os
import glob
import cv2
import tqdm
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
import shutil
%matplotlib inline
log_dir="./Myfont/dataset/fontimage"
img_files=sorted(glob.glob(os.path.join(log_dir,"*_AA.png")))[18614:18814]
category=["普通","囲み文字","文字列","絵","その他"]
for cat in category:
    0
    
    try:
        os.makedirs(os.path.join(log_dir,cat))
    except FileExistsError:
        pass
for i in tqdm.tqdm(img_files,total=len(img_files)):
#     print(i)
    img=Image.open(i,"r")
#     plt.imshow(np.array(img))
#     plt.show()
#     idx=int(input(str(i)+"----"+"０普通 １囲み文字 ２文字列 ３絵 ４その他"))
    idx=0
    font_list=sorted(glob.glob(i[:-7]+"*"))
    l=len(font_list)
    
    if l!=52:
        print("out",font_list)
    
#     for ff in font_list:
#         shutil.copy(ff, os.path.join(log_dir,category[idx]))

  8%|▊         | 15/200 [00:09<01:56,  1.59it/s]

out ['./Myfont/dataset/fontimage/ywft-motown-condensed_AA.png', './Myfont/dataset/fontimage/ywft-motown-condensed_BB.png', './Myfont/dataset/fontimage/ywft-motown-condensed_CC.png', './Myfont/dataset/fontimage/ywft-motown-condensed_DD.png', './Myfont/dataset/fontimage/ywft-motown-condensed_EE.png', './Myfont/dataset/fontimage/ywft-motown-condensed_FF.png', './Myfont/dataset/fontimage/ywft-motown-condensed_GG.png', './Myfont/dataset/fontimage/ywft-motown-condensed_HH.png', './Myfont/dataset/fontimage/ywft-motown-condensed_II.png', './Myfont/dataset/fontimage/ywft-motown-condensed_JJ.png', './Myfont/dataset/fontimage/ywft-motown-condensed_KK.png', './Myfont/dataset/fontimage/ywft-motown-condensed_LL.png', './Myfont/dataset/fontimage/ywft-motown-condensed_MM.png', './Myfont/dataset/fontimage/ywft-motown-condensed_NN.png', './Myfont/dataset/fontimage/ywft-motown-condensed_OO.png', './Myfont/dataset/fontimage/ywft-motown-condensed_PP.png', './Myfont/dataset/fontimage/ywft-motown-condensed_Q

 20%|██        | 40/200 [00:25<01:39,  1.61it/s]

out ['./Myfont/dataset/fontimage/zag_AA.png', './Myfont/dataset/fontimage/zag_BB.png', './Myfont/dataset/fontimage/zag_CC.png', './Myfont/dataset/fontimage/zag_DD.png', './Myfont/dataset/fontimage/zag_EE.png', './Myfont/dataset/fontimage/zag_FF.png', './Myfont/dataset/fontimage/zag_GG.png', './Myfont/dataset/fontimage/zag_HH.png', './Myfont/dataset/fontimage/zag_II.png', './Myfont/dataset/fontimage/zag_JJ.png', './Myfont/dataset/fontimage/zag_KK.png', './Myfont/dataset/fontimage/zag_LL.png', './Myfont/dataset/fontimage/zag_MM.png', './Myfont/dataset/fontimage/zag_NN.png', './Myfont/dataset/fontimage/zag_OO.png', './Myfont/dataset/fontimage/zag_PP.png', './Myfont/dataset/fontimage/zag_QQ.png', './Myfont/dataset/fontimage/zag_RR.png', './Myfont/dataset/fontimage/zag_SS.png', './Myfont/dataset/fontimage/zag_TT.png', './Myfont/dataset/fontimage/zag_UU.png', './Myfont/dataset/fontimage/zag_VV.png', './Myfont/dataset/fontimage/zag_WW.png', './Myfont/dataset/fontimage/zag_XX.png', './Myfont/d

 27%|██▋       | 54/200 [00:33<01:31,  1.60it/s]

out ['./Myfont/dataset/fontimage/zan_AA.png', './Myfont/dataset/fontimage/zan_BB.png', './Myfont/dataset/fontimage/zan_CC.png', './Myfont/dataset/fontimage/zan_DD.png', './Myfont/dataset/fontimage/zan_EE.png', './Myfont/dataset/fontimage/zan_FF.png', './Myfont/dataset/fontimage/zan_GG.png', './Myfont/dataset/fontimage/zan_HH.png', './Myfont/dataset/fontimage/zan_II.png', './Myfont/dataset/fontimage/zan_JJ.png', './Myfont/dataset/fontimage/zan_KK.png', './Myfont/dataset/fontimage/zan_LL.png', './Myfont/dataset/fontimage/zan_MM.png', './Myfont/dataset/fontimage/zan_NN.png', './Myfont/dataset/fontimage/zan_OO.png', './Myfont/dataset/fontimage/zan_PP.png', './Myfont/dataset/fontimage/zan_QQ.png', './Myfont/dataset/fontimage/zan_RR.png', './Myfont/dataset/fontimage/zan_SS.png', './Myfont/dataset/fontimage/zan_TT.png', './Myfont/dataset/fontimage/zan_UU.png', './Myfont/dataset/fontimage/zan_VV.png', './Myfont/dataset/fontimage/zan_WW.png', './Myfont/dataset/fontimage/zan_XX.png', './Myfont/d

 34%|███▎      | 67/200 [00:41<01:23,  1.59it/s]

out ['./Myfont/dataset/fontimage/zar-brush-gothic_AA.png', './Myfont/dataset/fontimage/zar-brush-gothic_BB.png', './Myfont/dataset/fontimage/zar-brush-gothic_CC.png', './Myfont/dataset/fontimage/zar-brush-gothic_DD.png', './Myfont/dataset/fontimage/zar-brush-gothic_EE.png', './Myfont/dataset/fontimage/zar-brush-gothic_FF.png', './Myfont/dataset/fontimage/zar-brush-gothic_GG.png', './Myfont/dataset/fontimage/zar-brush-gothic_HH.png', './Myfont/dataset/fontimage/zar-brush-gothic_II.png', './Myfont/dataset/fontimage/zar-brush-gothic_JJ.png', './Myfont/dataset/fontimage/zar-brush-gothic_KK.png', './Myfont/dataset/fontimage/zar-brush-gothic_LL.png', './Myfont/dataset/fontimage/zar-brush-gothic_MM.png', './Myfont/dataset/fontimage/zar-brush-gothic_NN.png', './Myfont/dataset/fontimage/zar-brush-gothic_OO.png', './Myfont/dataset/fontimage/zar-brush-gothic_PP.png', './Myfont/dataset/fontimage/zar-brush-gothic_QQ.png', './Myfont/dataset/fontimage/zar-brush-gothic_RR.png', './Myfont/dataset/fonti

 36%|███▌      | 71/200 [00:44<01:22,  1.57it/s]

out ['./Myfont/dataset/fontimage/zar2-script-thin_AA.png', './Myfont/dataset/fontimage/zar2-script-thin_BB.png', './Myfont/dataset/fontimage/zar2-script-thin_CC.png', './Myfont/dataset/fontimage/zar2-script-thin_DD.png', './Myfont/dataset/fontimage/zar2-script-thin_EE.png', './Myfont/dataset/fontimage/zar2-script-thin_FF.png', './Myfont/dataset/fontimage/zar2-script-thin_GG.png', './Myfont/dataset/fontimage/zar2-script-thin_HH.png', './Myfont/dataset/fontimage/zar2-script-thin_II.png', './Myfont/dataset/fontimage/zar2-script-thin_JJ.png', './Myfont/dataset/fontimage/zar2-script-thin_KK.png', './Myfont/dataset/fontimage/zar2-script-thin_LL.png', './Myfont/dataset/fontimage/zar2-script-thin_MM.png', './Myfont/dataset/fontimage/zar2-script-thin_NN.png', './Myfont/dataset/fontimage/zar2-script-thin_OO.png', './Myfont/dataset/fontimage/zar2-script-thin_PP.png', './Myfont/dataset/fontimage/zar2-script-thin_QQ.png', './Myfont/dataset/fontimage/zar2-script-thin_RR.png', './Myfont/dataset/fonti

 39%|███▉      | 78/200 [00:48<01:17,  1.58it/s]

out ['./Myfont/dataset/fontimage/zeal_AA.png', './Myfont/dataset/fontimage/zeal_BB.png', './Myfont/dataset/fontimage/zeal_CC.png', './Myfont/dataset/fontimage/zeal_DD.png', './Myfont/dataset/fontimage/zeal_EE.png', './Myfont/dataset/fontimage/zeal_FF.png', './Myfont/dataset/fontimage/zeal_GG.png', './Myfont/dataset/fontimage/zeal_HH.png', './Myfont/dataset/fontimage/zeal_II.png', './Myfont/dataset/fontimage/zeal_JJ.png', './Myfont/dataset/fontimage/zeal_KK.png', './Myfont/dataset/fontimage/zeal_LL.png', './Myfont/dataset/fontimage/zeal_MM.png', './Myfont/dataset/fontimage/zeal_NN.png', './Myfont/dataset/fontimage/zeal_OO.png', './Myfont/dataset/fontimage/zeal_PP.png', './Myfont/dataset/fontimage/zeal_QQ.png', './Myfont/dataset/fontimage/zeal_RR.png', './Myfont/dataset/fontimage/zeal_SS.png', './Myfont/dataset/fontimage/zeal_TT.png', './Myfont/dataset/fontimage/zeal_UU.png', './Myfont/dataset/fontimage/zeal_VV.png', './Myfont/dataset/fontimage/zeal_WW.png', './Myfont/dataset/fontimage/z

 52%|█████▏    | 104/200 [01:05<01:00,  1.58it/s]

out ['./Myfont/dataset/fontimage/zest_AA.png', './Myfont/dataset/fontimage/zest_BB.png', './Myfont/dataset/fontimage/zest_CC.png', './Myfont/dataset/fontimage/zest_DD.png', './Myfont/dataset/fontimage/zest_EE.png', './Myfont/dataset/fontimage/zest_FF.png', './Myfont/dataset/fontimage/zest_GG.png', './Myfont/dataset/fontimage/zest_HH.png', './Myfont/dataset/fontimage/zest_II.png', './Myfont/dataset/fontimage/zest_JJ.png', './Myfont/dataset/fontimage/zest_KK.png', './Myfont/dataset/fontimage/zest_LL.png', './Myfont/dataset/fontimage/zest_MM.png', './Myfont/dataset/fontimage/zest_NN.png', './Myfont/dataset/fontimage/zest_OO.png', './Myfont/dataset/fontimage/zest_PP.png', './Myfont/dataset/fontimage/zest_QQ.png', './Myfont/dataset/fontimage/zest_RR.png', './Myfont/dataset/fontimage/zest_SS.png', './Myfont/dataset/fontimage/zest_TT.png', './Myfont/dataset/fontimage/zest_UU.png', './Myfont/dataset/fontimage/zest_VV.png', './Myfont/dataset/fontimage/zest_WW.png', './Myfont/dataset/fontimage/z

 58%|█████▊    | 117/200 [01:13<00:52,  1.58it/s]

out ['./Myfont/dataset/fontimage/ziggy-sans_AA.png', './Myfont/dataset/fontimage/ziggy-sans_BB.png', './Myfont/dataset/fontimage/ziggy-sans_CC.png', './Myfont/dataset/fontimage/ziggy-sans_DD.png', './Myfont/dataset/fontimage/ziggy-sans_EE.png', './Myfont/dataset/fontimage/ziggy-sans_FF.png', './Myfont/dataset/fontimage/ziggy-sans_GG.png', './Myfont/dataset/fontimage/ziggy-sans_HH.png', './Myfont/dataset/fontimage/ziggy-sans_II.png', './Myfont/dataset/fontimage/ziggy-sans_JJ.png', './Myfont/dataset/fontimage/ziggy-sans_KK.png', './Myfont/dataset/fontimage/ziggy-sans_LL.png', './Myfont/dataset/fontimage/ziggy-sans_MM.png', './Myfont/dataset/fontimage/ziggy-sans_NN.png', './Myfont/dataset/fontimage/ziggy-sans_OO.png', './Myfont/dataset/fontimage/ziggy-sans_PP.png', './Myfont/dataset/fontimage/ziggy-sans_QQ.png', './Myfont/dataset/fontimage/ziggy-sans_RR.png', './Myfont/dataset/fontimage/ziggy-sans_SS.png', './Myfont/dataset/fontimage/ziggy-sans_TT.png', './Myfont/dataset/fontimage/ziggy-s

 60%|██████    | 120/200 [01:15<00:50,  1.59it/s]

out ['./Myfont/dataset/fontimage/zim_AA.png', './Myfont/dataset/fontimage/zim_BB.png', './Myfont/dataset/fontimage/zim_CC.png', './Myfont/dataset/fontimage/zim_DD.png', './Myfont/dataset/fontimage/zim_EE.png', './Myfont/dataset/fontimage/zim_FF.png', './Myfont/dataset/fontimage/zim_GG.png', './Myfont/dataset/fontimage/zim_HH.png', './Myfont/dataset/fontimage/zim_II.png', './Myfont/dataset/fontimage/zim_JJ.png', './Myfont/dataset/fontimage/zim_KK.png', './Myfont/dataset/fontimage/zim_LL.png', './Myfont/dataset/fontimage/zim_MM.png', './Myfont/dataset/fontimage/zim_NN.png', './Myfont/dataset/fontimage/zim_OO.png', './Myfont/dataset/fontimage/zim_PP.png', './Myfont/dataset/fontimage/zim_QQ.png', './Myfont/dataset/fontimage/zim_RR.png', './Myfont/dataset/fontimage/zim_SS.png', './Myfont/dataset/fontimage/zim_TT.png', './Myfont/dataset/fontimage/zim_UU.png', './Myfont/dataset/fontimage/zim_VV.png', './Myfont/dataset/fontimage/zim_WW.png', './Myfont/dataset/fontimage/zim_XX.png', './Myfont/d

 63%|██████▎   | 126/200 [01:19<00:46,  1.60it/s]

out ['./Myfont/dataset/fontimage/zinc-italian-sg_AA.png', './Myfont/dataset/fontimage/zinc-italian-sg_BB.png', './Myfont/dataset/fontimage/zinc-italian-sg_CC.png', './Myfont/dataset/fontimage/zinc-italian-sg_DD.png', './Myfont/dataset/fontimage/zinc-italian-sg_EE.png', './Myfont/dataset/fontimage/zinc-italian-sg_FF.png', './Myfont/dataset/fontimage/zinc-italian-sg_GG.png', './Myfont/dataset/fontimage/zinc-italian-sg_HH.png', './Myfont/dataset/fontimage/zinc-italian-sg_II.png', './Myfont/dataset/fontimage/zinc-italian-sg_JJ.png', './Myfont/dataset/fontimage/zinc-italian-sg_KK.png', './Myfont/dataset/fontimage/zinc-italian-sg_LL.png', './Myfont/dataset/fontimage/zinc-italian-sg_MM.png', './Myfont/dataset/fontimage/zinc-italian-sg_NN.png', './Myfont/dataset/fontimage/zinc-italian-sg_OO.png', './Myfont/dataset/fontimage/zinc-italian-sg_PP.png', './Myfont/dataset/fontimage/zinc-italian-sg_QQ.png', './Myfont/dataset/fontimage/zinc-italian-sg_RR.png', './Myfont/dataset/fontimage/zinc-italian-

 68%|██████▊   | 136/200 [01:25<00:39,  1.60it/s]

out ['./Myfont/dataset/fontimage/zion-train-cyrillic_AA.png', './Myfont/dataset/fontimage/zion-train-cyrillic_BB.png', './Myfont/dataset/fontimage/zion-train-cyrillic_CC.png', './Myfont/dataset/fontimage/zion-train-cyrillic_DD.png', './Myfont/dataset/fontimage/zion-train-cyrillic_EE.png', './Myfont/dataset/fontimage/zion-train-cyrillic_FF.png', './Myfont/dataset/fontimage/zion-train-cyrillic_GG.png', './Myfont/dataset/fontimage/zion-train-cyrillic_HH.png', './Myfont/dataset/fontimage/zion-train-cyrillic_II.png', './Myfont/dataset/fontimage/zion-train-cyrillic_JJ.png', './Myfont/dataset/fontimage/zion-train-cyrillic_KK.png', './Myfont/dataset/fontimage/zion-train-cyrillic_LL.png', './Myfont/dataset/fontimage/zion-train-cyrillic_MM.png', './Myfont/dataset/fontimage/zion-train-cyrillic_NN.png', './Myfont/dataset/fontimage/zion-train-cyrillic_OO.png', './Myfont/dataset/fontimage/zion-train-cyrillic_PP.png', './Myfont/dataset/fontimage/zion-train-cyrillic_QQ.png', './Myfont/dataset/fontimag

 78%|███████▊  | 156/200 [01:37<00:27,  1.60it/s]

out ['./Myfont/dataset/fontimage/zombie-rot-drippy_AA.png', './Myfont/dataset/fontimage/zombie-rot-drippy_BB.png', './Myfont/dataset/fontimage/zombie-rot-drippy_CC.png', './Myfont/dataset/fontimage/zombie-rot-drippy_DD.png', './Myfont/dataset/fontimage/zombie-rot-drippy_EE.png', './Myfont/dataset/fontimage/zombie-rot-drippy_FF.png', './Myfont/dataset/fontimage/zombie-rot-drippy_GG.png', './Myfont/dataset/fontimage/zombie-rot-drippy_HH.png', './Myfont/dataset/fontimage/zombie-rot-drippy_II.png', './Myfont/dataset/fontimage/zombie-rot-drippy_JJ.png', './Myfont/dataset/fontimage/zombie-rot-drippy_KK.png', './Myfont/dataset/fontimage/zombie-rot-drippy_LL.png', './Myfont/dataset/fontimage/zombie-rot-drippy_MM.png', './Myfont/dataset/fontimage/zombie-rot-drippy_NN.png', './Myfont/dataset/fontimage/zombie-rot-drippy_OO.png', './Myfont/dataset/fontimage/zombie-rot-drippy_PP.png', './Myfont/dataset/fontimage/zombie-rot-drippy_QQ.png', './Myfont/dataset/fontimage/zombie-rot-drippy_RR.png', './My

 80%|████████  | 161/200 [01:41<00:24,  1.61it/s]

out ['./Myfont/dataset/fontimage/zona-black-slab_AA.png', './Myfont/dataset/fontimage/zona-black-slab_BB.png', './Myfont/dataset/fontimage/zona-black-slab_CC.png', './Myfont/dataset/fontimage/zona-black-slab_DD.png', './Myfont/dataset/fontimage/zona-black-slab_EE.png', './Myfont/dataset/fontimage/zona-black-slab_FF.png', './Myfont/dataset/fontimage/zona-black-slab_GG.png', './Myfont/dataset/fontimage/zona-black-slab_HH.png', './Myfont/dataset/fontimage/zona-black-slab_II.png', './Myfont/dataset/fontimage/zona-black-slab_JJ.png', './Myfont/dataset/fontimage/zona-black-slab_KK.png', './Myfont/dataset/fontimage/zona-black-slab_LL.png', './Myfont/dataset/fontimage/zona-black-slab_MM.png', './Myfont/dataset/fontimage/zona-black-slab_NN.png', './Myfont/dataset/fontimage/zona-black-slab_OO.png', './Myfont/dataset/fontimage/zona-black-slab_PP.png', './Myfont/dataset/fontimage/zona-black-slab_QQ.png', './Myfont/dataset/fontimage/zona-black-slab_RR.png', './Myfont/dataset/fontimage/zona-black-sl

 82%|████████▏ | 164/200 [01:42<00:22,  1.60it/s]

out ['./Myfont/dataset/fontimage/zone-52_AA.png', './Myfont/dataset/fontimage/zone-52_BB.png', './Myfont/dataset/fontimage/zone-52_CC.png', './Myfont/dataset/fontimage/zone-52_DD.png', './Myfont/dataset/fontimage/zone-52_EE.png', './Myfont/dataset/fontimage/zone-52_FF.png', './Myfont/dataset/fontimage/zone-52_GG.png', './Myfont/dataset/fontimage/zone-52_HH.png', './Myfont/dataset/fontimage/zone-52_II.png', './Myfont/dataset/fontimage/zone-52_JJ.png', './Myfont/dataset/fontimage/zone-52_KK.png', './Myfont/dataset/fontimage/zone-52_LL.png', './Myfont/dataset/fontimage/zone-52_MM.png', './Myfont/dataset/fontimage/zone-52_NN.png', './Myfont/dataset/fontimage/zone-52_OO.png', './Myfont/dataset/fontimage/zone-52_PP.png', './Myfont/dataset/fontimage/zone-52_QQ.png', './Myfont/dataset/fontimage/zone-52_RR.png', './Myfont/dataset/fontimage/zone-52_SS.png', './Myfont/dataset/fontimage/zone-52_TT.png', './Myfont/dataset/fontimage/zone-52_UU.png', './Myfont/dataset/fontimage/zone-52_VV.png', './My

 98%|█████████▊| 197/200 [02:03<00:01,  1.59it/s]

out ['./Myfont/dataset/fontimage/zygo_AA.png', './Myfont/dataset/fontimage/zygo_BB.png', './Myfont/dataset/fontimage/zygo_CC.png', './Myfont/dataset/fontimage/zygo_DD.png', './Myfont/dataset/fontimage/zygo_EE.png', './Myfont/dataset/fontimage/zygo_FF.png', './Myfont/dataset/fontimage/zygo_GG.png', './Myfont/dataset/fontimage/zygo_HH.png', './Myfont/dataset/fontimage/zygo_II.png', './Myfont/dataset/fontimage/zygo_JJ.png', './Myfont/dataset/fontimage/zygo_KK.png', './Myfont/dataset/fontimage/zygo_LL.png', './Myfont/dataset/fontimage/zygo_MM.png', './Myfont/dataset/fontimage/zygo_NN.png', './Myfont/dataset/fontimage/zygo_OO.png', './Myfont/dataset/fontimage/zygo_PP.png', './Myfont/dataset/fontimage/zygo_QQ.png', './Myfont/dataset/fontimage/zygo_RR.png', './Myfont/dataset/fontimage/zygo_SS.png', './Myfont/dataset/fontimage/zygo_TT.png', './Myfont/dataset/fontimage/zygo_UU.png', './Myfont/dataset/fontimage/zygo_VV.png', './Myfont/dataset/fontimage/zygo_WW.png', './Myfont/dataset/fontimage/z

100%|██████████| 200/200 [02:05<00:00,  1.59it/s]


In [70]:
import numpy as np
x=np.array([[[1,0.9,0.2],[0.2,0.2,0.2],[0.2,0.2,1]],[[0.1,0.1,0.2],[0.2,0.2,0.2],[0.2,0.2,0.2]]])
# x=np.array([[1,1,0.2],[0.2,0.2,0.2],[0.2,0.2,0.2]]).reshape(-1,3,3)
print(x)
shape=x.shape
x=x.reshape(x.shape[0],-1)
b=np.dot(x.T,x)
print(b)
for r in range(b.shape[0]):
    b[r]=b[r]/np.linalg.norm(b[r],ord=3)
print(b)
a_map=b.T
out=np.dot(x,a_map.T)
out=out.reshape(*shape)
print(out.round(2))

[[[1.  0.9 0.2]
  [0.2 0.2 0.2]
  [0.2 0.2 1. ]]

 [[0.1 0.1 0.2]
  [0.2 0.2 0.2]
  [0.2 0.2 0.2]]]
[[1.01 0.91 0.22 0.22 0.22 0.22 0.22 0.22 1.02]
 [0.91 0.82 0.2  0.2  0.2  0.2  0.2  0.2  0.92]
 [0.22 0.2  0.08 0.08 0.08 0.08 0.08 0.08 0.24]
 [0.22 0.2  0.08 0.08 0.08 0.08 0.08 0.08 0.24]
 [0.22 0.2  0.08 0.08 0.08 0.08 0.08 0.08 0.24]
 [0.22 0.2  0.08 0.08 0.08 0.08 0.08 0.08 0.24]
 [0.22 0.2  0.08 0.08 0.08 0.08 0.08 0.08 0.24]
 [0.22 0.2  0.08 0.08 0.08 0.08 0.08 0.08 0.24]
 [1.02 0.92 0.24 0.24 0.24 0.24 0.24 0.24 1.04]]
[[0.7075249  0.63747293 0.15411433 0.15411433 0.15411433 0.15411433
  0.15411433 0.15411433 0.71453009]
 [0.70708396 0.63715258 0.15540307 0.15540307 0.15540307 0.15540307
  0.15540307 0.15540307 0.71485412]
 [0.66911471 0.6082861  0.24331444 0.24331444 0.24331444 0.24331444
  0.24331444 0.24331444 0.72994333]
 [0.66911471 0.6082861  0.24331444 0.24331444 0.24331444 0.24331444
  0.24331444 0.24331444 0.72994333]
 [0.66911471 0.6082861  0.24331444 0.24331444 0.243

In [59]:
print(x)


[[1.  1.  0.2 0.1 0.1 0.1 0.1 0.1 0.1]]


In [98]:
def clean2noise(label, T):
    probs = torch.index_select(T, 0, label)
    print(probs)
    m = torch.distributions.categorical.Categorical(probs)
    return m.sample()


def noise2clean(label, T):
    T_trans = T.transpose(0, 1)
    T_trans = T_trans / torch.sum(T_trans, dim=1, keepdim=True)
    print(T_trans)
    return clean2noise(label, T_trans)

In [99]:
import torch
label=torch.tensor([1])
T=torch.tensor([[0.6,0.2,0.2],[0.1,0.8,0.1],[0.1,0.3,0.6]])
noise2clean(label,T)

tensor([[0.7500, 0.1250, 0.1250],
        [0.1538, 0.6154, 0.2308],
        [0.2222, 0.1111, 0.6667]])
tensor([[0.1538, 0.6154, 0.2308]])


tensor([1])

In [4]:
list(range(2))

[0, 1]

In [8]:
import numpy as np
d = np.array([-1,-1,-1])
np.where(d==-1)[0]

array([0, 1, 2])

In [3]:
list = [0,0,0,0]
list.append(1)